#ifndef TRANSFORMARE_DIN_POSTORDINE_IN_INORDINE_H_INCLUDED
#define TRANSFORMARE_DIN_POSTORDINE_IN_INORDINE_H_INCLUDED

using namespace std;
string Transformare_InOrdine(string ExpInordine);
#endif // TRANSFORMARE_DIN_POSTORDINE_IN_INORDINE_H_INCLUDED
